name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8        

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-

    - name: Run Unit Tests with Jacoco and PIT
      run: xvfb-run mvn verify
      working-directory: ./expense-tracker-app

    - name: Archive Surefire Test Report and Site
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: surefire-report
        path: |
          expense-tracker-app/target/surefire-reports
          expense-tracker-app/target/site/surefire

    - name: Archive JaCoCo Report and Site
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: jacoco-report
        path: expense-tracker-app/target/site/jacoco

    - name: Archive PIT Report and Site
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: pit-report
        path: |
          expense-tracker-app/target/pit-reports
          expense-tracker-app/target/site/pitest

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 1.8        

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-

    - name: Run Integration Tests
      run: xvfb-run mvn verify -Pintegration-test
      working-directory: ./expense-tracker-app

    - name: Archive Failsafe Test Report and Site
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: failsafe-report
        path: |
          expense-tracker-app/target/failsafe-reports
          expense-tracker-app/target/site/failsafe

    - name: Archive Maven Site
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: maven-site
        path: expense-tracker-app/target/site
