name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8        
    
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    
    - name: Run Unit Tests with Jacoco and PIT
      run: xvfb-run mvn verify site -Punit-test
      working-directory: expense-tracker-app
    
    - name: Archive Unit Test Reports and Site
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: unit-test-reports
        path: |
          target/surefire-reports/*
          target/site/jacoco/*
          target/pit-reports/*  
          target/site
          
          
  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    
    steps:
    - uses: actions/checkout@v2 
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8        
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    
    - name: Run Integration Tests
      run: xvfb-run mvn verify -Pintegration-test
      working-directory: expense-tracker-app
    
    - name: Archive Integration Test Reports and Site
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: integration-test-reports
        path: |
          target/failsafe-reports/*
          target/site

