name: Java CI with coversall Maven

on:
  push:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      # test against several Java versions:
      matrix:
        include:
          - java: 8
            additional-maven-args: "-Pcoveralls -DrepoToken=$COVERALLS_REPO_TOKEN coveralls:report"

          
    name: Build with Java ${{ matrix.java }} on Linux 
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'       
    
    - name: Cache Maven package
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    
    - name: Run coversall
      run:  xvfb-run mvn verify ${{matrix.additional-maven-args}}
      working-directory: expense-tracker-app
      env: 
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
    


          